### ISSUE TITLE
Warning message while executing service_check.py

### ISSUE THREAD

**Issue by NoFWayMan** [steven-dfheinz/dfhz_elk_mpack#2]
At the end of adding elasticsearch service in the Ambari (2.7.4) Service Wizard to my HDP Stack (3.1.4) i received a warning message about execution of "service_check.py" script: 
SyntaxError: from __future__ imports must occur at the beginning of the file

After a short search, I found out that the imports from the future module must be located at the beginning of the file.
So i move "from __future__ import print_function" line from "service_check.py" script to the top and warning message is gone.

**Comment by steven-matison** [comment]
Nice one, thanks for the feedback.
